definitions:
  user.TransferMoneyDTO:
    properties:
      amount:
        type: integer
      from:
        type: integer
      to:
        type: integer
    type: object
  user.UserChargeMoneyDTO:
    properties:
      amount:
        type: integer
      id:
        type: integer
    type: object
  user.UserRemoveMoneyDTO:
    properties:
      amount:
        type: integer
      id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/v1/charge:
    post:
      consumes:
      - application/json
      description: add certain amount of money to user
      parameters:
      - description: Charge money
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/user.UserChargeMoneyDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "418":
          description: I'm a teapot
        "500":
          description: Internal Server Error
      summary: Charge balance
  /api/v1/remove:
    post:
      consumes:
      - application/json
      description: remove certain amount of user`s money
      parameters:
      - description: Remove money
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/user.UserRemoveMoneyDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "418":
          description: I'm a teapot
        "500":
          description: Internal Server Error
      summary: Decrease user balance
  /api/v1/transfer:
    post:
      consumes:
      - application/json
      description: transfer money from one user to another
      parameters:
      - description: Remove money
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/user.TransferMoneyDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "418":
          description: I'm a teapot
        "500":
          description: Internal Server Error
      summary: Transfer Money
  /users:
    post:
      description: Create user with default values
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "418":
          description: I'm a teapot
        "500":
          description: Internal Server Error
      summary: Create user
  /users/{id}:
    get:
      description: Get user balance by id
      parameters:
      - description: User id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "418":
          description: I'm a teapot
        "500":
          description: Internal Server Error
      summary: Get user balance
swagger: "2.0"
