basePath: /
definitions:
  dto.ShowUserIdDTO:
    properties:
      user_id:
        type: integer
    type: object
  dto.TransferMoneyDTO:
    properties:
      amount:
        type: integer
      from:
        type: integer
      to:
        type: integer
    type: object
  entity.User:
    properties:
      balance:
        type: integer
      id:
        type: integer
    type: object
  user.UserChargeMoneyDTO:
    properties:
      amount:
        type: integer
      id:
        type: integer
    type: object
  user.UserRemoveMoneyDTO:
    properties:
      amount:
        type: integer
      id:
        type: integer
    type: object
host: localhost:30001
info:
  contact: {}
  description: This is a sample banking service.
  title: Swagger Example API
  version: "1.1"
paths:
  /api/v1/charge/:
    post:
      consumes:
      - application/json
      description: add certain amount of money to user
      parameters:
      - description: Charge money
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/user.UserChargeMoneyDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "418":
          description: I'm a teapot
        "500":
          description: Internal Server Error
      summary: Charge balance
      tags:
      - user
  /api/v1/remove/:
    post:
      consumes:
      - application/json
      description: remove certain amount of user`s money
      parameters:
      - description: Remove money
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/user.UserRemoveMoneyDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "418":
          description: I'm a teapot
        "500":
          description: Internal Server Error
      summary: Decrease user balance
      tags:
      - user
  /api/v1/transfer/:
    post:
      consumes:
      - application/json
      description: transfer money from one user to another
      parameters:
      - description: Remove money
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/dto.TransferMoneyDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "418":
          description: I'm a teapot
        "500":
          description: Internal Server Error
      summary: Transfer Money
      tags:
      - user
  /users/:
    post:
      description: Create user with default values
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.ShowUserIdDTO'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "418":
          description: I'm a teapot
        "500":
          description: Internal Server Error
      summary: Create user
      tags:
      - user
  /users/{id}/:
    get:
      description: Get user balance by id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "418":
          description: I'm a teapot
        "500":
          description: Internal Server Error
      summary: Get user balance
      tags:
      - user
swagger: "2.0"
