info:
  contact: {}
paths:
  /api/v1/charge:
    post:
      consumes:
      - application/json
      description: add certain amount of money to user
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Charge balance
  /api/v1/remove:
    post:
      consumes:
      - application/json
      description: remove certain amount of user`s money
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Decrease user balance
  /api/v1/transfer:
    get:
      consumes:
      - application/json
      description: transfer money from one user to another
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Transfer Money
  /users:
    post:
      description: Create user with default values
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "500":
          description: Internal Server Error
      summary: Create user
  /users/:id:
    get:
      description: Get user by id
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get user
swagger: "2.0"
